### ISSUE TITLE
Misleading entity recognition when using parenthesis. 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin-js#2]
![image](https://cloud.githubusercontent.com/assets/837037/2704657/e06ed9da-c470-11e3-8758-5f9da450d598.png)

When writing "Google(code-named..." the recognised entity is <Google Code> rather than Google. 

The same occurs when adding the white space "Google (code-named...".

**Comment by ziodave** [comment]
Old widget, closing.
