### ISSUE TITLE
New entity cannot be selected

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-plugin-js#9]
![image](https://cloud.githubusercontent.com/assets/837037/4031762/23217c04-2c6a-11e4-88a3-194800fd1127.png)
As I'm writing the documentation I noticed that after manually adding the entity "WordLift" in a test post I cannot select it from the reconciliation panel (on Chrome).

See screenshot of the error from the console.  

![image](https://cloud.githubusercontent.com/assets/837037/4031784/6088a626-2c6a-11e4-9c11-3a3fa70a69e9.png)

**Comment by ziodave** [comment]
Old widget, closing this one.
